### ISSUE TITLE
Consider Using crypto Library for Salt Generation

### ISSUE THREAD

**Issue by a6b8** [Trac-Systems/tap-protocol-token-auth-boilerplate#1]
Using Math.random() for salt generation introduces potential security risks due to its predictability. I suggest utilizing the crypto library's randomBytes() for salt generation.

**Comment by TracSystems** [comment]
Yep, that's why in the comments of the boilerplate it is stated to better use something like inscription IDs for uniqueness.
So best is:

- for authority creation: randomBytes or equivalent 
- for redeeming: an inscription id (if applicable) that the redemption refers to, or a nonce managed by the authority if the authority relies on determinism for re-indexing purposes.

We will update the boilerplate for people to make that more obvious. Thx.
